# nonk8s
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  disableDefaultCNI: true
  kubeProxyMode: none

nodes:
  - role: control-plane
    image: kindest/node:v1.30.0
    labels:
      grafysi.app.allowed/ingress: true
    extraMounts:
      - hostPath: ${GRAFYSI_CONFIG}/local-pv-store
        containerPath: /local-pv-store
      
  - role: worker
    image: kindest/node:v1.30.0
    labels:
      grafysi.app.allowed/kafka: true
    extraMounts:
      - hostPath: ${GRAFYSI_CONFIG}/local-pv-store
        containerPath: /local-pv-store
    
  - role: worker
    image: kindest/node:v1.30.0
    labels:
      grafysi.app.allowed/neo4j: true
    extraMounts:
      - hostPath: ${GRAFYSI_CONFIG}/local-pv-store
        containerPath: /local-pv-store

  - role: worker
    image: kindest/node:v1.30.0
    labels:
      grafysi.app.allowed/neo4j: true
    extraMounts:
      - hostPath: ${GRAFYSI_CONFIG}/local-pv-store
        containerPath: /local-pv-store
#
#  - role: worker
#    image: kindest/node:v1.30.0
#    labels:
#      grafysi.server.allowed/neo4j: true
#
#  - role: worker
#    image: kindest/node:v1.30.0
#    labels:
#      grafysi.server.allowed/neo4j: true
