kubeProxyReplacement: "true"
ipam:
  mode: "kubernetes"

hubble:
  # -- Enable Hubble (true by default).
  enabled: true

  relay:
    # -- Enable Hubble Relay (requires hubble.enabled=true)
    enabled: true

  ui:
    # -- Whether to enable the Hubble UI.
    enabled: true

    # -- Defines base url prefix for all hubble-ui http requests.
    # It needs to be changed in case if ingress for hubble-ui is configured under some sub-path.
    # Trailing `/` is required for custom path, ex. `/service-map/`
    #baseUrl: "/hubble-ui/"

    # -- hubble-ui ingress configuration.
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "haproxy"
        #haproxy.org/path-rewrite: "/"
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      className: "haproxy"
      hosts:
        - hubble-ui.obs.grafysi.local
