apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: share-local-sc2
provisioner: rancher.io/local-path
parameters:
  nodePath: /pv-store/share
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: Immediate
reclaimPolicy: Delete