name: gfs-infra
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: gfs-storage-server
    volumes:
      - $GRAFYSI_CONFIG/storage-server/data:/data
#    ports:
#      - 9000:9000
#      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'abcd1234'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    networks:
      gfs-network:
        ipv4_address: ${GRAFYSI_STORAGE_SERVER_HOST}
    restart: always

networks:
  gfs-network:
    name: ${GRAFYSI_DOCKER_NODE_VLAN_NET}
    external: true